# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 47d06d82fb5538da1605a6e648bb5d1773209d727c6aadb65861599566399c7183ce72c52ae6a75675797bb9c12ef0744e14c5efbdbb787acbba83fa06312df9

test:
  secret_key_base: b06f65e3b9ed936bc26dfdafaa6c40a96cad53bbfef88f19fb5b4591a9e1e65d71ba28c9a696ee4113b52478fc2d9ebc8a6e60b272fd858383c9ff66b0ac53d3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
